# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end

  config.vm.define "control-plane" do |node|
    node.vm.hostname = "control-plane"
    node.vm.network "private_network", ip: "192.168.56.10", hostname: true
    node.vm.provision "shell", name: "Tag Controller", inline: "echo 'control' > /var/role"
    node.vm.provision "file", source: "custom-resources.yaml", destination: "/tmp/custom-resources.yaml"
  end

  (1..2).each do |i|
    hostname = "node-#{'%02d' % i}"
    config.vm.define "#{hostname}" do |node|
      node.vm.hostname = "#{hostname}"
      node.vm.network "private_network", ip: "192.168.56.#{10 + i}", hostname: true
      node.vm.provision "shell", name: "Tag Node", inline: "echo 'node' > /var/role"
    end
  end
    config.vm.provision "shell", path: "../scripts/user-nico.sh"
    config.vm.provision "shell", name: "allow-bridge-nf-traffic", path: "allow-bridge-nf-traffic.sh"
    config.vm.provision "shell", name: "install-essential-tools", path: "install-essential-tools.sh"
    config.vm.provision "file", source: "containerd.service", destination: "/tmp/containerd.service"
    config.vm.provision "shell", name: "install-containerd", path: "install-containerd.sh"
    config.vm.provision "shell", name: "install-kubeadm", path: "install-kubeadm.sh"
    config.vm.provision "shell", name: "update-kubelet-config", path: "update-kubelet-config.sh", args: ["eth1"]
    #config.vm.provision "shell", name: "init-controlplane", path: "init-controlplane.sh"
end
