# -*- mode: ruby -*-
# vi: set ft=ruby :

servers = [
    {
        :name => "forgejo",
        :box => "cloud-image/ubuntu-26.04",
        :mem => "16384",
        :disk => "30GB",
        :cpu => "12",
        :mac => "08002742e957"
    },
]

Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.hostname = opts[:name]
            config.vm.network "public_network", mac: opts[:mac]
            # Changed private IP to .22 to avoid conflict with GitLab (.21)
            config.vm.network "private_network", ip: "192.168.56.22"

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]
                # Sets the Public NIC (Adapter 2) to use the Paravirtualized Network driver
                v.customize ["modifyvm", :id, "--nictype2", "virtio"]
                # --------------------------------------

            end
            # Resize disk using vagrant-disksize plugin
            # remember to run: vagrant plugin install vagrant-disksize
            config.disksize.size = opts[:disk]

            config.vm.provision "shell", path: "../scripts/user-nico.sh"
            config.vm.provision "shell", path: "../scripts/install-docker.sh"
            config.vm.provision "shell", path: "install-forgejo.sh"

        end
    end
end
