# -*- mode: ruby -*-
# vi: set ft=ruby :

#Vagrant::DEFAULT_SERVER_URL.replace('https://vagrantcloud.com')
servers = [
    {
        :name => "gitlab",
        :box => "generic/ubuntu2204",
        :mem => "4096",
        :cpu => "6"
    },
]


Vagrant.configure("2") do |config|

    servers.each do |opts|
        config.vm.define opts[:name] do |config|

            config.vm.box = opts[:box]
            config.vm.hostname = opts[:name]
            config.vm.network "public_network", use_dhcp_assigned_default_route: true

            config.vm.provider "virtualbox" do |v|

                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--memory", opts[:mem]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpu]]

            end

            config.vm.provision "shell", path: "../scripts/user-nico.sh"
            config.vm.provision "shell", path: "../scripts/install-gitlab.sh"

        end
    end
end 